version: 1.0.{build}
image:
  - Visual Studio 2019
platform:
  - x64
configuration:
  - Debug
  - Release
before_build:
  - cmd: git submodule update --init
  - cmd: cmake -H. -B build -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\installdir
build:
  verbosity: detailed
build_script:
  - cmd: cmake --build build --config %CONFIGURATION%
test_script:
  - cmd: cmake --build build --target RUN_TESTS --config %CONFIGURATION% 
after_build:
  - cmd: cmake --build build --target INSTALL --config %CONFIGURATION%
before_package:
  - cd %APPVEYOR_BUILD_FOLDER%
  - set BUILD_ARCHIVE=itensor-%CONFIGURATION%-MSVC-x64.zip
  - cmd: 7z a %BUILD_ARCHIVE% installdir
  - appveyor PushArtifact %BUILD_ARCHIVE%
artifacts:
  - path: '*.zip'
deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release of itensor $(APPVEYOR_REPO_TAG_NAME) tag created by AppVeyor build $(APPVEYOR_BUILD_VERSION)'
    artifact: /.*\.zip/
    auth_token:
      secure: nVwU/APPL08DuFnAmsPc5hwD9Bl90M4UgEfNi31cTb/jtJLALyZBa+JeO3hhP26O
    draft: false
    prerelease: false
    on:
      branch: main
      APPVEYOR_REPO_TAG: true
