name: Build and Test
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            BLA_VENDOR: OpenBLAS
            test_target: test
          - os: ubuntu-latest
            BLA_VENDOR: Generic
            test_target: test
          - os: macos-latest
            BLA_VENDOR: Apple
            test_target: test
          - os: windows-latest
            BLA_VENDOR: OpenBLAS
            test_target: RUN_TESTS
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Check out submodule
      run: git submodule update --init
    - name: Install OpenBLAS
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.BLA_VENDOR == 'OpenBLAS' }}
      run: sudo apt-get install libopenblas-dev liblapacke-dev
    - name: Install LAPACK
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.BLA_VENDOR == 'Generic' }}
      run: sudo apt-get install liblapack-dev liblapacke-dev
    - name: Make CMake build directory
      run: cmake -B build -DBLA_VENDOR=${{ matrix.BLA_VENDOR }}
    - name: Build Debug
      run: cmake --build build --config Debug
    - name: Test Debug
      if: ${{ matrix.os != 'windows-latest' }}
      run: cmake --build build --target ${{ matrix.test_target }} --config Debug
    - name: Build Release
      run: cmake --build build --config Release
    - name: Test Release
      run: cmake --build build --target ${{ matrix.test_target }} --config Release