name: CI
on: [push, pull_request]
jobs:
  build-ubuntu:
    strategy:
      matrix:
        BLA_VENDOR: ["OpenBLAS", "Generic"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check out submodule
      run: git submodule update --init
    - name: Install dependencies
      run: sudo apt-get install libopenblas-dev liblapack-dev liblapacke-dev
    - name: Make CMake build directory
      run: cmake -B build -DCMAKE_INSTALL_PREFIX=/opt/itensor -DBLA_VENDOR=${{ matrix.BLA_VENDOR }}
    - name: Build Debug
      run: cmake --build build --config Debug
    - name: Test Debug
      run: cmake --build build --target test --config Debug
    - name: Build Release
      run: cmake --build build --config Release
    - name: Test Release
      run: cmake --build build --target test --config Release
    - name: Install Release
      run: cmake --build build --target install --config Release
    - name: Package
      run: |
        export BUILD_ARCHIVE=itensor-${{ matrix.BLA_VENDOR }}-ubuntu-x86_64.tgz
        tar cvzf "$BUILD_ARCHIVE" /opt/itensor
        ls -al
        pwd
        apt-cache search mkl

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check out submodule
      run: git submodule update --init
    - name: Make CMake build directory
      run: cmake -B build -DCMAKE_INSTALL_PREFIX=/opt/itensor -DBLA_VENDOR=Apple
    - name: Build Debug
      run: cmake --build build --config Debug
    - name: Test Debug
      run: cmake --build build --target test --config Debug
    - name: Build Release
      run: cmake --build build --config Release
    - name: Test Release
      run: cmake --build build --target test --config Release
    - name: Install Release
      run: cmake --build build --target install --config Release
    - name: Package
      run: |
        export BUILD_ARCHIVE=itensor-Accelerate-macos-x86_64.tgz
        tar cvzf "$BUILD_ARCHIVE" /opt/itensor
        ls -al
        pwd


    
        

      