name: CI
on: [push, pull_request]
jobs:
  build-ubuntu:
    strategy:
      matrix:
        BLA_VENDOR: ["OpenBLAS", "Generic"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check out submodule
      run: git submodule update --init
    - name: Install dependencies
      run: sudo apt-get install libopenblas-dev liblapack-dev liblapacke-dev
    - name: Make CMake build directory
      run: cmake -B build -DCMAKE_INSTALL_PREFIX=/opt/itensor-${{ github.sha }} -DBLA_VENDOR=${{ matrix.BLA_VENDOR }}
    - name: Build Debug
      run: cmake --build build --config Debug
    - name: Test Debug
      run: cmake --build build --target test --config Debug
    - name: Build Release
      run: cmake --build build --config Release
    - name: Test Release
      run: cmake --build build --target test --config Release
    - name: Install Release
      run: cmake --build build --target install --config Release
    - name: Package
      run: |
        export BUILD_ARCHIVE=itensor-${{ github.sha }}-${{ matrix.BLA_VENDOR }}-ubuntu-x86_64.tgz
        tar cvzf "$BUILD_ARCHIVE" -C /opt itensor-${{ github.sha }}
    - uses: actions/upload-artifact@v2
      with:
        name: itensor-${{ github.sha }}-${{ matrix.BLA_VENDOR }}-ubuntu-x86_64.tgz
        path: itensor-${{ github.sha }}-${{ matrix.BLA_VENDOR }}-ubuntu-x86_64.tgz
  
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check out submodule
      run: git submodule update --init
    - name: Make CMake build directory
      run: cmake -B build -DCMAKE_INSTALL_PREFIX=/opt/itensor-${{ github.sha }} -DBLA_VENDOR=Apple
    - name: Build Debug
      run: cmake --build build --config Debug
    - name: Test Debug
      run: cmake --build build --target test --config Debug
    - name: Build Release
      run: cmake --build build --config Release
    - name: Test Release
      run: cmake --build build --target test --config Release
    - name: Install Release
      run: sudo cmake --build build --target install --config Release
    - name: Package
      run: |
        export BUILD_ARCHIVE=itensor-${{ github.sha }}-Accelerate-macos-x86_64.tgz
        tar cvzf "$BUILD_ARCHIVE" -C /opt itensor-${{ github.sha }}
    - uses: actions/upload-artifact@v2
      with:
        name: itensor-${{ github.sha }}-Accelerate-macos-x86_64.tgz
        path: itensor-${{ github.sha }}-Accelerate-macos-x86_64.tgz
          

      