name: Deb package
on: [push]
jobs:
  release-deb:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            BLA_VENDOR: OpenBLAS
            platform: ubuntu
            asset_ext: deb
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Check out submodule
      run: git submodule update --init
    - name: Install OpenBLAS
      run: sudo apt-get install libopenblas-dev liblapacke-dev
    - name: Make CMake build directory
      run: cmake -B build -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/installdir/usr -DBLA_VENDOR=${{ matrix.BLA_VENDOR }}
    - name: Install Release
      run: cmake --build build --target install --config Release
    - name: Create DEB configuration
      run: |
        mkdir -p ${{ github.workspace }}/installdir/DEBIAN/
        cat > ${{ github.workspace }}/installdir/DEBIAN/control <<EOS
        Package: itensor-dev
        Version: 3.1.5
        Section: science
        Priority: optional
        Architecture: amd64
        Essential: no
        Depends: liblapacke-dev, libopenblas-dev
        Maintainer: Kyungmin Lee <kyungmin.lee.42@gmail.com>
        Description: ITensor package
        EOS
    - name: Package (deb)
      run: dpkg-deb --build ${{ github.workspace }}/installdir itensor-dev_${{ github.sha }}_amd64.deb
    - uses: actions/upload-artifact@v2
      with:
        name: itensor-dev_${{ github.sha }}_amd64.deb
        path: itensor-dev_${{ github.sha }}_amd64.deb
    # - name: Upload Release Asset
    #   id: upload-release-asset 
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
    #   with:
    #     upload_url: ${{ needs.create_release.outputs.upload_url }}
    #     asset_path: itensor-${{ github.sha }}-${{ matrix.BLA_VENDOR }}-${{ matrix.platform }}-x86_64.${{ matrix.asset_ext }}
    #     asset_name: itensor-${{ github.sha }}-${{ matrix.BLA_VENDOR }}-${{ matrix.platform }}-x86_64.${{ matrix.asset_ext }}
    #     asset_content_type: application/${{ matrix.asset_ext }}